### ISSUE TITLE
Documentation of qiskit.optimization.INFINITY looks strange

### ISSUE THREAD

**Issue by t-imamichi** [qiskit-community/qiskit-optimization#10]
### What is the expected enhancement?

`INFINITY` is a constant to represent the infinite number.
The current description seems to be strange.
> Convert a string or number to a floating point number, if possible.

https://qiskit.org/documentation/stubs/qiskit.optimization.INFINITY.html#infinity

**Comment by 3yakuya** [comment]
That link is dead, I suppose this issue could be closed?

**Comment by woodsp-ibm** [comment]
The docs were moved and it looks like redirect that was in place has been discontinued. It can be seen here now

https://qiskit.org/ecosystem/optimization/apidocs/qiskit_optimization.html

![image](https://github.com/qiskit-community/qiskit-optimization/assets/40241007/859fd782-9b57-452d-b27f-6bf93f2b6018)
