### ISSUE TITLE
Enable using ``QAOAClient`` as input to the warmstart QAOA algorithm

### ISSUE THREAD

**Issue by Cryoris** [qiskit-community/qiskit-optimization#358]
### What should we add?

The ``WarmStartQAOAOptimizer`` currently only allows a ``QAOA`` object as input for the QAOA algorithm. It would be great to extend this to also support the ``QAOAClient`` so that we can use warmstarting in context of the runtime.

This could be done by either
* explictly allowing the ``QAOAClient`` as input (easiest solution), or 
* derive the ``QAOAClient`` from ``QAOA`` (might be the cleaner solution)

**Comment by t-imamichi** [comment]
QAOAClient has been removed #542
