### ISSUE TITLE
QAOARuntime with CVAR optimization

### ISSUE THREAD

**Issue by ghellstern** [qiskit-community/qiskit-optimization#515]
### Environment

<html><body>

Qiskit Software | Version
-- | --
qiskit-terra | 0.24.0
qiskit-aer | 0.12.0
qiskit-ignis | 0.6.0
qiskit-ibmq-provider | 0.20.2
qiskit | 0.43.0
qiskit-nature | 0.3.1
qiskit-finance | 0.2.0
qiskit-optimization | 0.5.0
qiskit-machine-learning | 0.2.1

Python version | 3.7.9
Python compiler | GCC 7.3.0
Python build | default, Aug 31 2020 12:42:55
OS | Linux
CPUs | 4
Memory (Gb) | 15.650867462158203

</body>
</html>

### What is happening?

In the tutorial https://qiskit.org/ecosystem/optimization/tutorials/12_qaoa_runtime.html QAOAClient produces an error when alpha=0.75 ist used. When removing alpha everythin is fine. See attached notebook.

[QAOA_client.zip](https://github.com/Qiskit/qiskit-optimization/files/11529326/QAOA_client.zip)

### How can we reproduce the issue?

See Notebook

### What should happen?

QAOAClient should work with alpha<1.0

**Comment by Cryoris** [comment]
I can reproduce the above and looking at the error codes it seems the `CVaRMeasurement` is given an unsupported input: 
```
[...]
2023-05-22T12:47:42.644038453Z     raise ValueError("Unsupported input to CVaRMeasurement.eval:", type(front))
2023-05-22T12:47:42.644047641Z ValueError: ('Unsupported input to CVaRMeasurement.eval:', )
```
