### ISSUE TITLE
Transform a Hamiltonian Produced by Qiskit Quadratic Program to.ising() function into a PyQubo Hamiltonian

### ISSUE THREAD

**Issue by OuCheng-Fu** [qiskit-community/qiskit-optimization#556]
Hello everyone, I am trying to convert an Ising Hamiltonian produced by to_ising() from Quadratic Program of Qiskit to a PyQubo Hamiltonian mentioned in the tutorials: https://pyqubo.readthedocs.io/en/stable/getting_started.html and my code is as the following:
`def Qiskit_Operator_to_PyQubo(num, QiskitOp):
    # num = number of variables, QiskitOp = input Qiskit Operator
    from qiskit.opflow import I, ListOp, OperatorBase, PauliOp, PauliSumOp, SummedOp
    from qiskit.quantum_info import Pauli
    from qiskit_optimization.exceptions import QiskitOptimizationError
    
    # Create Spin variables with respect to variable numbers from Quadratic Program
    # Create a dictionary to store the spin variables
    spin_variables_dict = {}
    for j in range(1, num+1):
        variable_name = f"s{j}"
        spin_variables_dict[variable_name] = Spin("s" + str(j))

    # Qiskit Operator transformation using from_ising()
    if isinstance(QiskitOp, PauliSumOp):
        QiskitOp = QiskitOp.to_pauli_op()

    # No support for ListOp yet, this can be added in future
    # pylint: disable=unidiomatic-typecheck
    if type(QiskitOp) == ListOp:
        raise NotImplementedError(
            "Conversion of a ListOp is not supported, convert each "
            "operator in the ListOp separately."
        )

    offset = 0.0
    if not isinstance(QiskitOp, SummedOp):
        pauli_list = [QiskitOp.to_pauli_op()]
    else:
        pauli_list = QiskitOp.to_pauli_op()

    # prepare a matrix of coefficients of Pauli terms
    # `pauli_coeffs_diag` is the diagonal part
    # `pauli_coeffs_triu` is the upper triangular part
    pauli_coeffs_diag = [0.0] * QiskitOp.num_qubits
    pauli_coeffs_triu = {}
    # Prepare PyQubo Hamiltonian
    H_PyQubo_part_linear = 0
    H_PyQubo_part_quadratic = 0

    for pauli_op in pauli_list:
        pauli_op = pauli_op.to_pauli_op()
        pauli = pauli_op.primitive
        coeff = pauli_op.coeff

        if not math.isclose(coeff.imag, 0.0, abs_tol=1e-10):
            raise QiskitOptimizationError(f"Imaginary coefficient exists: {pauli_op}")

        if np.any(pauli.x):
            raise QiskitOptimizationError(f"Pauli X or Y exists in the Pauli term: {pauli}")
        
        # indices of Pauli Zs in the Pauli term
        z_index = np.where(pauli.z)[0]
        num_z = len(z_index)

        # Construct PyQubo Hamiltonian
        spin_var_product = 1

        if num_z == 0:
            offset += coeff.real
        elif num_z == 1:
            pauli_coeffs_diag[z_index[0]] = coeff.real
            if variable_name == f"s{z_index[0]}":
             H_PyQubo_part_linear += (pauli_coeffs_diag[z_index[0]])*(spin_variables_dict[variable_name])
        elif num_z == 2:
            pauli_coeffs_triu[z_index[0], z_index[1]] = coeff.real
            # multiply two spins
            spin_var_names = [f's{z_index[0]}', f's{z_index[1]}']
            
            for variable_name in spin_var_names:
                if variable_name in spin_variables_dict:
                    spin_var_product *= spin_variables_dict[variable_name]
            
            H_PyQubo_part_quadratic += (pauli_coeffs_triu[z_index[0], z_index[1]])*spin_var_product
        else:
            raise QiskitOptimizationError(
                f"There are more than 2 Pauli Zs in the Pauli term: {pauli}"
            )

    H_PyQubo = offset + H_PyQubo_part_linear + H_PyQubo_part_quadratic
    return H_PyQubo

H = Qiskit_Operator_to_PyQubo(num_var, qubitOp)
print("PyQubo Hamiltonian:", H)`
I use the source code of "from_ising()" and created dynamic variables with respect to PyQubo Spin, but when I substitute the MaxCut Hamiltonian
`Offset: -2.5
Ising Hamiltonian:
0.5 * IIIZZ
+ 0.5 * IIZZI
+ 0.5 * IZZII
+ 0.5 * ZIIIZ
+ 0.5 * ZZIII`
into the code it reproduced PyQubo Hamiltonian:
`PyQubo Hamiltonian: (0.000000 + (0.500000 * ((1.000000 * Spin('s3')) * Spin('s4'))) + (0.500000 * (1.000000 * Spin('s4'))) + (0.500000 * ((1.000000 * Spin('s2')) * Spin('s3'))) + (0.500000 * ((1.000000 * Spin('s1')) * Spin('s2'))) + 0.000000 + (0.500000 * (1.000000 * Spin('s1'))))`
which is not the correct Hamiltonian. How should I modify the function?

**Comment by OuCheng-Fu** [comment]
If one thinks that converting Hamiltonians are too complicated, how can one turn a Quadratic Program of Qiskit directly to a Quadratic Program of PyQubo?

**Comment by woodsp-ibm** [comment]
I am closing this, as you figured out your problem, from Slack here where you also brought up the above
https://qiskit.slack.com/archives/CB6C24TPB/p1694498835187899
https://qiskit.slack.com/archives/CB6C24TPB/p1694499132977739

> I found the problem. It is from the settings of spin variables. Both Python and PyQubo had their range and spin variables start from label zero, not one. So after changing range(1, num) to range(num) the problem is solved

**Comment by OuCheng-Fu** [comment]
Thank you.
