### ISSUE TITLE
cannot import "BaseBackent" from "qiskit.providers" 

### ISSUE THREAD

**Issue by JohnyMarley** [qiskit-community/qiskit-optimization#577]
### Environment

- **Qiskit Optimization version**: 0.6.0
- **Python version**: 3.12.0
- **Operating system**:  linux

### What is happening?

I am trying to run the quiskit optimization example from:
https://qiskit.org/ecosystem/optimization/tutorials/02_converters_for_quadratic_programs.html

And get the following import error: 

ImportError: cannot import name 'BaseBackend' from 'qiskit.providers' (/home/jdara/anaconda3/envs/quant4/lib/python3.12/site-packages/qiskit/providers/__init__.py)

### How can we reproduce the issue?

First run these pip commands: 

pip install qiskit
pip install qiskit-ibm-runtime
pip install qiskit[visualization]
pip install qiskit-optimization
pip install 'qiskit-optimization[cplex]'
pip install 'qiskit-optimization[cvx]'
pip install 'qiskit-optimization[matplotlib]'

Then run in a jupyternotebook: 

from qiskit_optimization.algorithms import CplexOptimizer
cplex_optimizer = CplexOptimizer()

This results in this error: 

ImportError: cannot import name 'BaseBackend' from 'qiskit.providers' (/home/jdara/anaconda3/envs/quant4/lib/python3.12/site-packages/qiskit/providers/__init__.py)

I am running in a anaconda environment if this should be relevant 

### What should happen?

I would expect the import not to go wrong

**Comment by Sofranac-Boro** [comment]
I can confirm that I can reproduce the error after following the same steps for python3.12. What happened in my environment is that `pip install 'qiskit-optimization[cplex]'` downgrades the `qiskit-optimization` back to 0.3.2
```
Installing collected packages: qiskit-optimization
  Attempting uninstall: qiskit-optimization
    Found existing installation: qiskit-optimization 0.6.0
    Uninstalling qiskit-optimization-0.6.0:
      Successfully uninstalled qiskit-optimization-0.6.0
Successfully installed qiskit-optimization-0.3.2
```

**Comment by JohnyMarley** [comment]
Thanks for the reply and help! :+1:

**Comment by SarevalasaBharathkumar** [comment]
i am facing an error with the import line
from qiskit_machine_learning.algorithms import VQR
output: 
ImportError: cannot import name 'BackendV1' from 'qiskit.providers' (/home/rguktrkvalley/anaconda3/envs/quantum_env/lib/python3.10/site-packages/qiskit/providers/__init__.py)

Description: I tried to uninstall and install packages. And also setting up in a separate environment but still i am facing the issue cannot import name backendve from qiskit.providers

could you please help to resolve this issue.
