### ISSUE TITLE
Documentation contains outdated CPLEX version 

### ISSUE THREAD

**Issue by larsschellhas** [qiskit-community/qiskit-optimization#591]
### Environment

Irrelevant

### What is happening?

The documentation states "Currently there is no python **3.9** version of CPLEX. In this case, the CPLEX install command will have no effect."

### How can we reproduce the issue?

See Readme.md

### What should happen?

It should say "Currently there is no python **3.12** version of CPLEX. In this case, the CPLEX install command will have no effect."

**Comment by woodsp-ibm** [comment]
Fixed by #592 which has now been merged.
