### ISSUE TITLE
Solving a bug in the MagicRounding class of QRAO

### ISSUE THREAD

**Issue by yksat** [qiskit-community/qiskit-optimization#626]
### Environment

- **Qiskit Optimization version**: 0.6.1
- **Python version**: 3.10
- **Operating system**: Ubuntu 20.04

### What is happening?

The problem arises in the method, ``_unpack_measurement_outcome,'' in MagicRounding that decodes the classical bits from a quantum state.

In the current version, we can find in lines 234-235:
``` 
#iterate in order over decision variables
for q, op in var2op.values():
```
This code iterates in the order in which values were added to the dictionary, rather than in the order of the decision variables.
So, the line 235 should be modified as follows:
```diff
# iterate in order over decision variables
- for q, op in var2op.values():
+ for var in range(len(var2op)):
+     q, op = var2op[var]
```

### How can we reproduce the issue?

In the following, the maxcut problem for the one-dimensional graph with 3 nodes is solved.
The maxcut value should be 2, but the result returns the cut value of 1.

```
import networkx as nx
from qiskit import QuantumCircuit
from qiskit.primitives import Sampler
from qiskit_optimization.applications import Maxcut
from qiskit_optimization.algorithms.qrao import (
    QuantumRandomAccessEncoding,
    MagicRounding,
)
from qiskit_optimization.algorithms.qrao.rounding_common import RoundingContext


# Create one-dimensional graph whose maxcut is trivial
graph = nx.Graph()
graph.add_nodes_from([0, 1, 2])
graph.add_edges_from([(0, 1), (1, 2)])
maxcut = Maxcut(graph)
problem = maxcut.to_quadratic_program()
print(problem.prettyprint())


# Encode the QUBO problem into a Hamiltonian
encoding = QuantumRandomAccessEncoding(max_vars_per_qubit=1)
encoding.encode(problem)


# Construct a quantum circuit that prepares the optimal state.
circuit = QuantumCircuit(3)
circuit.x(2-encoding.var2op[1][0]) # since the endianness of var2op and the endianness of the qubit numbers are reversed.


# Perform magic state rounding
rounding_context = RoundingContext(encoding=encoding, expectation_values=0, circuit=circuit)
sampler = Sampler(options={"shots": 1})
magic_rounding = MagicRounding(sampler=sampler)
results = magic_rounding.round(rounding_context)
print(results.samples[0])
```

### What should happen?

The above code should returns the maxcut value of 2.

### Any suggestions?

Modifying the lines 234-235 of MagicRounding will fix the bug.
It is also preferable to align the endianness of var2op with the endianness of the qubit numbers.

**Comment by t-imamichi** [comment]
Thank you for the bug report. Could you make a PR consisting of the following items?

- Bugfix (your suggestion in the description)
- Test case to catch the bug (you have one in the description)
- release note (https://github.com/qiskit-community/qiskit-optimization/blob/main/CONTRIBUTING.md#release-notes)
